[Unit]
After=network-online.target hostapd.service sys-subsystem-net-devices-wlx0013eff27090.device
Requires=hostapd.service

[Service]
ExecStartPre=
ExecStartPre=/bin/sleep 5
Restart=always
RestartSec=5
