# インターフェース
interface=wlx0013eff27090
driver=nl80211

# IoT SSID
ssid=<AP_name>

# 2.4GHz
hw_mode=g
channel=6
country_code=JP
ieee80211d=1
ieee80211n=1
wmm_enabled=1

# WPA2セキュリティ
auth_algs=1
wpa=2
wpa_passphrase=<passphrase>
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
rsn_pairwise=CCMP

# クライアント間分離
ap_isolate=1
